let GeoIPDB = _GetWatchlist("geoip");
Syslog
| where Facility in ("auth", "authpriv")
| where SyslogMessage contains "Invalid user" or SyslogMessage contains "Failed password" or SyslogMessage contains "from"
| extend SourceIP = extract(@"from ((?:\d{1,3}\.){3}\d{1,3})", 1, SyslogMessage)
| where isnotempty(SourceIP)
| where SourceIP == "134.209.194.172"
| where ProcessName == "sshd"
| order by TimeGenerated desc
| evaluate ipv4_lookup(GeoIPDB, SourceIP, network)
| project TimeGenerated, Computer,AttackerIP = SourceIP, cityname, countryname, latitude, longitude

//This KQL Query reveals where the IP Address is located and project is used to show only the columns needed
// _GetWatchlist() is used after creating the Watchlist
